site_name: TMDPDF

nav:
  - Home: index.md
  - API Documents: 
    - libtmdpdf: api/libtmdpdf.md
    - libtmdpdf.fit: api/libtmdpdf.fit.md
    - libtmdpdf.plot: api/libtmdpdf.plot.md
    - libtmdpdf.utils: api/libtmdpdf.utils.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_root_members_full_path: true
            show_object_full_path: true
            group_by_category: true
            show_submodules: true


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 6
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
      - toc.follow


repo_url: https://github.com/tanganke/tmdpdf

